import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import AuthProvider from "@/providers/AuthProvider";
import AuthContextProvider from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased gradient-bg`}
      >
        <AuthProvider>
          <AuthContextProvider>
            <header>
              <Navbar />
            </header>
            <main className="min-h-[calc(100vh-360px)]">{children}</main>

            <footer className="px-2.5 sm:px-0">
              <Footer />
            </footer>
          </AuthContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
